name: pollen_project
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.0.5
  - backcall=0.2.0
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - decorator=5.1.1
  - executing=0.8.3
  - ipython=8.2.0
  - jedi=0.18.1
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.17
  - libstdcxx-ng=9.3.0
  - matplotlib-inline=0.1.2
  - ncurses=6.3
  - numpy=1.20.3
  - openssl=1.1.1n
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - python=3.8.5
  - python-spams=2.6.1
  - python_abi=3.8
  - readline=8.1.2
  - scipy=1.5.3
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.2
  - stack_data=0.2.0
  - tk=8.6.11
  - traitlets=5.1.1
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - colorama==0.4.4
    - cryptography==37.0.1
    - flatbuffers==2.0
    - idna==3.3
    - importlib-metadata==4.11.3
    - jeepney==0.8.0
    - keyring==23.5.0
    - pillow==9.0.1
    - pkginfo==1.8.2
    - protobuf==3.19.4
    - python-dateutil==2.8.2
    - requests==2.27.1
    - secretstorage==3.3.2
    - staintools==2.1.2
    - torch==1.10.2
    - torchvision==0.11.3
    - zipp==3.8.0
